### ISSUE TITLE
docker-compose pull has no effect

### ISSUE THREAD

**Issue by tommymcguiver** [Nekroze/dab#420] opened 2019-12-05 03:38 UTC
### Describe the bug

docker-compose pull has no effect when your docker-compose.yml has build and image options

### To Reproduce

Steps to reproduce the behaviour:

```bash
bash$ export DAB_IMAGE_TAG="stable"
bash$ dab shell
3:35 @ dab $ cat >/tmp/docker-compose.test.yaml <<EOF
> version: '2.1'
> services:
>   watcher:
>     build: .
>     image: containous/whoami
> EOF
03:35 @ dab $ docker-compose -f docker-compose.test.yaml pull
03:35 @ dab $ docker images | grep 'containous/whoami' || echo "Not found"
Not found
```

### Expected behaviour

docker-compose pulls the correct file

### `dab version` output

```
Dab Version: 975e26f0ad88d5543f725b4fde908865043269ca
Server Version: 19.03.5
Runtimes: runc
Kernel Version: 4.18.0-80.7.1.el8_0.x86_64
Operating System: CentOS Linux 8 (Core)
Architecture: x86_64

```

### Additional context
Issue is not replicatable in latest.
'latest' has older version of docker-compose
```bash
[kenm@kenm-dev:~]$ docker pull nekroze/dab:latest
latest: Pulling from nekroze/dab
Digest: sha256:01b5b24e9b6aa6e49a7581b1cf7d7896c1bb4f7f1f43b6de6f1be212c3d3503b
Status: Image is up to date for nekroze/dab:latest
docker.io/nekroze/dab:latest
[kenm@kenm-dev:~]$ dab shell docker-compose --version
docker-compose version 1.24.1, build 4667896
```

https://github.com/docker/compose/releases/tag/1.25.1-rc1 fixes the issue.

**Comment by tommymcguiver** [comment] 2019-12-05 03:41
Suspect https://github.com/docker/compose/pull/7039 is the cause of the issue

**Comment by tommymcguiver** [comment] 2019-12-05 03:43
Happy to wait until release candidate is released.

**Comment by Nekroze** [comment] 2019-12-06 01:50
Weird that his updated landed on the stable branch image but not latest, I am using a latest that was built today too and it too is still on 1.24.1...

I will rebuild locally and if I get 1.24 again I will get docker hub to rebuild the stable image too which should put it back.

**Comment by Nekroze** [comment] 2019-12-06 01:54
Sadly that did not work. For now I will add a version specifier to ensure it does not use 1.25 or higher for now. We will just have to remove that once the upstream gets it back in working order, although there seems to be chatter about this being a design decision...

**Comment by Nekroze** [comment] 2019-12-06 03:06
I can confirm this is now fixed on the stable image tag

**Closed** 2019-12-06 03:06 UTC
Labels: bug
